"""Schema declaration implementation for Delta tables and foreign keys."""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from typing import Final

from delta_engine.application.properties import DELTA_PROPERTY_REGISTRY, Property
from delta_engine.domain.model import (
    ALL_ASPECTS,
    Array,
    Column,
    DataType,
    DesiredTable,
    ForeignKeyConstraint,
    Map,
    PrimaryKeyConstraint,
    QualifiedName,
    Struct,
    TableAspect,
)


class _SelfReference:
    """Sentinel marking a foreign key that references its own table."""

    __slots__ = ()

    def __repr__(self) -> str:
        return "Self"


Self: Final = _SelfReference()

METADATA_ASPECTS: Final[frozenset[TableAspect]] = frozenset(
    {
        TableAspect.TABLE_COMMENT,
        TableAspect.COLUMN_COMMENTS,
        TableAspect.COLUMN_TAGS,
        TableAspect.TABLE_TAGS,
        TableAspect.PRIMARY_KEY,
        TableAspect.FOREIGN_KEYS,
    }
)

# Delta permits these characters in column names only under column mapping.
_CHARACTERS_REQUIRING_COLUMN_MAPPING: Final[frozenset[str]] = frozenset(" ,;{}()\n\t=")

# Column names change data feed reserves for its own output columns.
_CDF_RESERVED_COLUMN_NAMES: Final[frozenset[str]] = frozenset(
    {"_change_type", "_commit_version", "_commit_timestamp"}
)

# Unity Catalog limits per securable object (a table and each of its
# columns are separate securables).
_MAX_TAGS_PER_SECURABLE: Final[int] = 50
_MAX_TAG_VALUE_LENGTH: Final[int] = 1000


def _validate_tags(subject: str, tags: Mapping[str, str]) -> None:
    if len(tags) > _MAX_TAGS_PER_SECURABLE:
        raise ValueError(
            f"{subject} declares {len(tags)} tags; Unity Catalog allows at"
            f" most {_MAX_TAGS_PER_SECURABLE} per securable"
        )
    for key, value in tags.items():
        if len(value) > _MAX_TAG_VALUE_LENGTH:
            raise ValueError(
                f"Tag {key!r} on {subject} has a {len(value)}-character"
                f" value; Unity Catalog allows at most {_MAX_TAG_VALUE_LENGTH}"
            )


def _column_declared_names(column: Column) -> tuple[str, ...]:
    """
    Return every name a column declares under Delta's naming rules.

    This is the column's own name, plus every struct field name reachable
    through nested ``Struct``/``Array``/``Map`` types (struct-in-array,
    struct-in-struct, and so on). The column's own name is returned bare;
    nested field names are returned as dotted paths from the column, e.g.
    ``"payload.order id"`` for a field named ``"order id"`` inside a struct
    column named ``"payload"``.
    """
    return (column.name, *_nested_field_paths(column.name, column.data_type))


def _nested_field_paths(path: str, data_type: DataType) -> tuple[str, ...]:
    """Recursively collect dotted struct-field paths reachable from `data_type`."""
    match data_type:
        case Struct(fields):
            paths: list[str] = []
            for field in fields:
                field_path = f"{path}.{field.name}"
                paths.append(field_path)
                paths.extend(_nested_field_paths(field_path, field.data_type))
            return tuple(paths)
        case Array(element):
            return _nested_field_paths(path, element)
        case Map(key, value):
            return _nested_field_paths(path, key) + _nested_field_paths(path, value)
        case _:
            return ()


@dataclass(frozen=True, slots=True)
class ForeignKey:
    """
    Public declaration of a foreign key relationship.

    Names the local columns and the table they reference. The referenced
    columns are always the referenced table's primary key, aligned positionally
    with ``local_columns`` in the referenced table's primary-key declaration
    order. The physical constraint name is generated by the engine and is not
    part of this declaration.

    ``references`` is another :class:`DeltaTable`, or the :data:`Self` sentinel
    for a self-referential key. See the architecture explanation doc for why the
    reference is an object rather than a name.
    """

    local_columns: Sequence[str]
    references: DeltaTable | _SelfReference

    def __post_init__(self) -> None:
        # Accept any sequence at the public boundary (users naturally pass
        # lists); store a tuple so the declaration stays immutable.
        object.__setattr__(self, "local_columns", tuple(self.local_columns))

    def _to_constraint(
        self,
        owner_name: QualifiedName,
        owner_columns: tuple[Column, ...],
        owner_primary_key: tuple[str, ...],
    ) -> ForeignKeyConstraint:
        """
        Lower this declaration into a domain constraint.

        Applies the lowering rules in order: the referenced table must declare
        a primary key, the local column count must match it, and each local
        column's data type must match its referenced column's. Local column
        existence is not checked here — the ``DesiredTable`` built right
        after enforces it.
        """
        referenced_table, referenced_columns, referenced_types = self._resolve_reference(
            owner_name, owner_columns, owner_primary_key
        )

        if not referenced_columns:
            raise ValueError(
                f"cannot infer referenced columns: {referenced_table} declares no primary key"
            )
        if len(self.local_columns) != len(referenced_columns):
            raise ValueError(
                "foreign key local column count must match the referenced primary key;"
                f" {owner_name} declares {len(self.local_columns)} local column(s)"
                f" but {referenced_table}'s primary key has {len(referenced_columns)}"
            )

        local_types = {column.name: column.data_type for column in owner_columns}
        for local_name, referenced_name in zip(self.local_columns, referenced_columns, strict=True):
            local_type = local_types.get(local_name)
            if local_type is None:
                continue  # local column existence is enforced when the DesiredTable is built
            referenced_type = referenced_types[referenced_name]
            if local_type != referenced_type:
                raise ValueError(
                    f"foreign key column type mismatch: {owner_name}.{local_name}"
                    f" is {local_type} but {referenced_table}.{referenced_name}"
                    f" is {referenced_type}"
                )

        return ForeignKeyConstraint.generate(
            owner_table_name=owner_name.name,
            local_columns=tuple(self.local_columns),
            referenced_table=referenced_table,
            referenced_columns=tuple(referenced_columns),
        )

    def _resolve_reference(
        self,
        owner_name: QualifiedName,
        owner_columns: tuple[Column, ...],
        owner_primary_key: tuple[str, ...],
    ) -> tuple[QualifiedName, tuple[str, ...], dict[str, DataType]]:
        """
        Resolve ``references`` to the referenced side of the constraint.

        Returns the referenced table's name, its primary-key columns (the
        columns this key references), and its column types by name. For
        :data:`Self` the enclosing table supplies all three — its own name,
        ``owner_primary_key``, and ``owner_columns`` — because the owner's
        ``DesiredTable`` does not exist yet while its foreign keys are being
        lowered. The returned mapping always covers every referenced column:
        primary-key columns are validated to exist on whichever table
        declares them.
        """
        match self.references:
            case _SelfReference():
                types = {column.name: column.data_type for column in owner_columns}
                return owner_name, owner_primary_key, types
            case DeltaTable() as target:
                desired = target.to_desired_table()
                types = {column.name: column.data_type for column in desired.columns}
                return desired.qualified_name, desired.primary_key_columns, types
            case _:
                raise TypeError(
                    f"foreign key references must be a DeltaTable or Self; got {self.references!r}"
                )


class DeltaTable:
    """
    Defines a Delta table schema.

    Note on dropping columns: Delta only permits ``ALTER TABLE ... DROP COLUMN``
    when ``delta.columnMapping.mode`` is ``name``. Declare it in ``properties``
    on any table whose columns may be dropped; a sync that drops a column
    without it fails at validation with a message naming the property.
    """

    def __init__(
        self,
        catalog: str,
        schema: str,
        name: str,
        columns: Iterable[Column],
        comment: str = "",
        properties: Mapping[str, str | None] | None = None,
        tags: Mapping[str, str] | None = None,
        partitioned_by: Iterable[str] = (),
        foreign_keys: Iterable[ForeignKey] | None = None,
        metadata_only: bool = False,
    ) -> None:
        """
        Initialise a DeltaTable definition.

        Args:
            catalog: Unity Catalog catalog name.
            schema: Schema (database) name within the catalog.
            name: Table name.
            columns: Ordered column declarations.
            comment: Table-level comment.
            properties: Delta/Spark table properties to manage.
            tags: Key/value tags to apply to the table.
            partitioned_by: Column names to partition by.
            foreign_keys: Foreign key relationships declared on this table.
            metadata_only: When ``True``, restricts the sync to catalog metadata:
                comments, tags, and key constraints. The full table is still
                declared — columns, properties, partitioning — but only
                metadata is deployed; the rest is never compared or changed,
                except that the live schema must match the declared columns
                exactly (structural drift fails validation).

        """
        user_properties = dict(properties or {})

        # Fast-fail on property keys this engine does not manage (e.g. typos).
        # None-valued assertions are validated too: asserting absence of an
        # unmanaged key is as meaningless as declaring it.
        unmanaged = [key for key in user_properties if key not in DELTA_PROPERTY_REGISTRY]
        if unmanaged:
            raise ValueError(
                f"Properties not managed by this engine: {', '.join(sorted(unmanaged))}"
            )

        # Fast-fail on malformed values; the definition owns the judgment
        # (including the exemption for None, which asserts absence).
        for key, declared_value in user_properties.items():
            rejection = DELTA_PROPERTY_REGISTRY[key].reject_declared_value(declared_value)
            if rejection is not None:
                raise ValueError(rejection)

        columns = tuple(columns)

        if not metadata_only and user_properties.get(Property.COLUMN_MAPPING_MODE) != "name":
            offending = [
                name
                for column in columns
                for name in _column_declared_names(column)
                if set(name) & _CHARACTERS_REQUIRING_COLUMN_MAPPING
            ]
            if offending:
                raise ValueError(
                    f"Column or struct field names {offending} contain characters Delta only"
                    " permits with column mapping. Declare"
                    f" properties={{'{Property.COLUMN_MAPPING_MODE}': 'name'}}"
                    " or rename the columns."
                )

        if not metadata_only and user_properties.get(Property.CHANGE_DATA_FEED) == "true":
            reserved = [
                column.name for column in columns if column.name in _CDF_RESERVED_COLUMN_NAMES
            ]
            if reserved:
                raise ValueError(
                    f"Column names {reserved} are reserved by change data feed."
                    " Rename them or do not enable"
                    f" {Property.CHANGE_DATA_FEED}."
                )

        table_tags = dict(tags or {})
        _validate_tags(f"table '{name}'", table_tags)
        for column in columns:
            _validate_tags(f"column '{column.name}'", column.tags)

        primary_key_columns = tuple(column.name for column in columns if column.primary_key)
        primary_key = (
            PrimaryKeyConstraint.generate(table_name=name, columns=primary_key_columns)
            if primary_key_columns
            else None
        )

        clustered_by = tuple(column.name for column in columns if column.cluster_key)

        qualified_name = QualifiedName(catalog, schema, name)
        lowered_foreign_keys = tuple(
            declaration._to_constraint(qualified_name, columns, primary_key_columns)
            for declaration in (foreign_keys or ())
        )

        # Building DesiredTable here enforces all domain invariants (non-empty
        # columns, unique names, partition columns must exist, FK local columns
        # must exist) at construction time rather than deferring them to
        # to_desired_table().
        self._desired_table = DesiredTable(
            qualified_name=qualified_name,
            columns=columns,
            comment=comment,
            properties=user_properties,
            tags=table_tags,
            partitioned_by=tuple(partitioned_by),
            clustered_by=clustered_by,
            primary_key=primary_key,
            foreign_keys=lowered_foreign_keys,
            managed_aspects=METADATA_ASPECTS if metadata_only else ALL_ASPECTS,
        )

    @property
    def catalog(self) -> str:
        """Unity Catalog catalog name."""
        return self._desired_table.qualified_name.catalog

    @property
    def schema(self) -> str:
        """Schema (database) name within the catalog."""
        return self._desired_table.qualified_name.schema

    @property
    def name(self) -> str:
        """Table name."""
        return self._desired_table.qualified_name.name

    @property
    def columns(self) -> tuple[Column, ...]:
        """Declared columns, in declaration order."""
        return self._desired_table.columns

    @property
    def comment(self) -> str:
        """Table-level comment (empty string when unset)."""
        return self._desired_table.comment

    @property
    def properties(self) -> Mapping[str, str | None]:
        """
        Declared table properties.

        A ``None`` value asserts the property must be absent from the table.
        """
        return self._desired_table.properties

    @property
    def tags(self) -> Mapping[str, str]:
        """Declared table tags."""
        return self._desired_table.tags

    @property
    def partitioned_by(self) -> tuple[str, ...]:
        """Partition column names, in declaration order."""
        return self._desired_table.partitioned_by

    @property
    def clustered_by(self) -> tuple[str, ...]:
        """Clustering key column names, in declaration order."""
        return self._desired_table.clustered_by

    @property
    def primary_key(self) -> tuple[str, ...]:
        """Column names declared as the primary key, in declaration order."""
        return self._desired_table.primary_key_columns

    @property
    def foreign_keys(self) -> tuple[ForeignKeyConstraint, ...]:
        """Foreign key constraints declared on this table."""
        return self._desired_table.foreign_keys

    def to_desired_table(self) -> DesiredTable:
        """Return the domain :class:`DesiredTable` for this table definition."""
        return self._desired_table
