"""Public API declaration for foreign key relationships."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Final

if TYPE_CHECKING:
    from delta_engine.api.table import DeltaTable


class _SelfReference:
    """Sentinel marking a foreign key that references its own table."""

    __slots__ = ()

    def __repr__(self) -> str:
        return "Self"


Self: Final = _SelfReference()


@dataclass(frozen=True, slots=True)
class ForeignKey:
    """
    Public declaration of a foreign key relationship.

    Names the local columns and the table they reference. The referenced
    columns are always the referenced table's primary key, aligned positionally
    with ``local_columns`` in the referenced table's primary-key declaration
    order. The physical constraint name is generated by the engine and is not
    part of this declaration.

    ``references`` is another :class:`~delta_engine.DeltaTable`, or the
    :data:`Self` sentinel for a self-referential key.
    """

    local_columns: tuple[str, ...]
    references: DeltaTable | _SelfReference
