"""Public API containers for describing a Delta table and its foreign keys."""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from types import MappingProxyType
from typing import ClassVar

from delta_engine.api.properties import MANAGED_PROPERTY_KEYS, Property
from delta_engine.domain.model import Column, DesiredTable, QualifiedName
from delta_engine.domain.model.foreign_key import ForeignKeyConstraint
from delta_engine.domain.model.primary_key import PrimaryKeyConstraint


class ForeignKey:
    """
    Declares a foreign key from this table's columns to another table's primary key.

    The referenced table is identified by its :class:`DeltaTable` object, not by
    name — a typo'd or unregistered reference is a Python error at definition
    time rather than a sync failure later. A consequence is that a table cannot
    reference itself (the object does not exist yet inside its own definition);
    self-referential foreign keys are not supported.

    The constraint name is generated by the engine
    (``{table}_{local_columns}_fk``); user-defined names are a future feature.
    """

    def __init__(
        self,
        local_columns: Iterable[str],
        references: DeltaTable,
        referenced_columns: Iterable[str],
    ) -> None:
        self.local_columns = tuple(local_columns)
        self.references = references
        self.referenced_columns = tuple(referenced_columns)


class DeltaTable:
    """
    Defines a Delta table schema.

    Note on dropping columns: Delta only permits ``ALTER TABLE ... DROP COLUMN``
    when ``delta.columnMapping.mode`` is ``name``, which is the default applied
    here. If you override that property to ``none``, a sync that removes a column
    will fail at execution time. Keep column mapping enabled on tables whose
    columns may be dropped.
    """

    default_properties: ClassVar[Mapping[str, str]] = MappingProxyType(
        {
            Property.COLUMN_MAPPING_MODE.value: "name",
        }
    )

    def __init__(
        self,
        catalog: str,
        schema: str,
        name: str,
        columns: Iterable[Column],
        comment: str = "",
        properties: dict[str, str] | None = None,
        tags: dict[str, str] | None = None,
        partitioned_by: Iterable[str] | None = None,
        foreign_keys: Iterable[ForeignKey] | None = None,
    ) -> None:
        user_properties = dict(properties or {})

        # Fast-fail on property keys this engine does not manage (e.g. typos)
        if user_properties:
            unmanaged = [k for k in user_properties if k not in MANAGED_PROPERTY_KEYS]
            if unmanaged:
                raise ValueError(
                    f"Properties not managed by this engine: {', '.join(sorted(unmanaged))}"
                )

        effective_properties = {**self.default_properties, **user_properties}

        columns = tuple(columns)
        primary_key_columns = tuple(column.name for column in columns if column.primary_key)
        primary_key = (
            PrimaryKeyConstraint(columns=primary_key_columns) if primary_key_columns else None
        )
        foreign_key_constraints = tuple(
            ForeignKeyConstraint(
                local_columns=foreign_key.local_columns,
                references=foreign_key.references.qualified_name,
                referenced_columns=foreign_key.referenced_columns,
            )
            for foreign_key in (foreign_keys or ())
        )

        # Building DesiredTable here enforces all domain invariants (non-empty
        # columns, unique names, partition columns must exist, FK local columns
        # must exist) at construction time rather than deferring them to
        # to_desired_table().
        self._desired_table = DesiredTable(
            qualified_name=QualifiedName(catalog, schema, name),
            columns=columns,
            comment=comment,
            properties=effective_properties,
            tags=dict(tags or {}),
            partitioned_by=tuple(partitioned_by) if partitioned_by is not None else (),
            primary_key=primary_key,
            foreign_keys=foreign_key_constraints,
        )

    @property
    def qualified_name(self) -> QualifiedName:
        """The table's fully qualified name (catalog.schema.name)."""
        return self._desired_table.qualified_name

    @property
    def effective_properties(self) -> Mapping[str, str]:
        """Defaults overlaid by user properties (user wins)."""
        return self._desired_table.properties

    @property
    def primary_key(self) -> tuple[str, ...]:
        """Column names declared as the primary key, in declaration order."""
        constraint = self._desired_table.primary_key
        return constraint.columns if constraint is not None else ()

    @property
    def foreign_keys(self) -> tuple[ForeignKeyConstraint, ...]:
        """Foreign key constraints declared on this table."""
        return self._desired_table.foreign_keys

    def to_desired_table(self) -> DesiredTable:
        """Return the domain :class:`DesiredTable` for this table definition."""
        return self._desired_table
