"""Behavioural tests for generating a declaration module from observed state."""

import pytest

from delta_engine.api.codegen import GenerationError, generate_module
from delta_engine.api.delta_table import DeltaTable
from delta_engine.domain.model import (
    Array,
    DataType,
    Date,
    Decimal,
    Integer,
    Long,
    Map,
    ObservedColumn,
    ObservedForeignKeyConstraint,
    ObservedPrimaryKeyConstraint,
    ObservedTable,
    QualifiedName,
    String,
    Struct,
    StructField,
    TableFeature,
    TableKind,
    Timestamp,
    data_type as data_type_module,
)
from delta_engine.domain.plan import diff_table
from delta_engine.domain.plan.actions import DropForeignKey

# Concrete samples for the data types whose constructors take arguments; every
# other DataType subclass is constructed bare. A new parametrised type fails
# here until a sample is added, keeping the renderer exhaustiveness pinned.
_PARAMETRIZED_SAMPLES: dict[type[DataType], DataType] = {
    Decimal: Decimal(10, 2),
    Array: Array(Struct([StructField("nested", String())])),
    Map: Map(String(), Array(Long())),
    Struct: Struct([StructField("first", Integer()), StructField("second", Timestamp())]),
}


def _concrete_data_types() -> tuple[type[DataType], ...]:
    # dataclass(slots=True) leaves abandoned pre-slots classes behind in
    # DataType.__subclasses__(), so enumerate the module namespace instead.
    return tuple(
        member
        for member in vars(data_type_module).values()
        if isinstance(member, type) and issubclass(member, DataType) and member is not DataType
    )


def _sample_data_types() -> tuple[DataType, ...]:
    return tuple(
        _PARAMETRIZED_SAMPLES.get(subclass) or subclass() for subclass in _concrete_data_types()
    )


def _import_declaration(source: str) -> DeltaTable:
    namespace: dict[str, object] = {}
    exec(compile(source, "<generated>", "exec"), namespace)
    (declared,) = namespace["all_tables"]  # type: ignore[misc]
    assert isinstance(declared, DeltaTable)
    return declared


def test_minimal_table_renders_an_importable_declaration_module() -> None:
    # Given
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "orders"),
        columns=(
            ObservedColumn("id", Integer(), nullable=False),
            ObservedColumn("note", String()),
        ),
    )

    # When
    module = generate_module(observed)

    # Then
    assert module.source == (
        "# Generated by: delta-engine generate dev.sales.orders\n"
        "from delta_engine.schema import Column, DeltaTable, Integer, String\n"
        "\n"
        "orders = DeltaTable(\n"
        '    catalog="dev",\n'
        '    schema="sales",\n'
        '    name="orders",\n'
        "    columns=[\n"
        '        Column("id", Integer(), nullable=False),\n'
        '        Column("note", String()),\n'
        "    ],\n"
        ")\n"
        "\n"
        "all_tables = (orders,)\n"
    )
    assert module.warnings == ()


def test_full_featured_table_renders_every_argument() -> None:
    # Given a table using every observable aspect
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "orders"),
        columns=(
            ObservedColumn("id", Long(), nullable=False, comment="Order identifier"),
            ObservedColumn("placed_on", Date(), tags={"pii": "false"}),
        ),
        comment="One row per order.",
        tags={"owner": "tom", "domain": "sales"},
        clustered_by=("id",),
        primary_key=ObservedPrimaryKeyConstraint(("id",), "orders_pk"),
        properties={"delta.enableChangeDataFeed": "true"},
    )

    # When
    module = generate_module(observed)

    # Then
    assert module.source == (
        "# Generated by: delta-engine generate dev.sales.orders\n"
        "from delta_engine.schema import Column, Date, DeltaTable, Long\n"
        "\n"
        "orders = DeltaTable(\n"
        '    catalog="dev",\n'
        '    schema="sales",\n'
        '    name="orders",\n'
        "    columns=[\n"
        '        Column("id", Long(), nullable=False, comment="Order identifier"),\n'
        '        Column("placed_on", Date(), tags={"pii": "false"}),\n'
        "    ],\n"
        '    comment="One row per order.",\n'
        '    properties={"delta.enableChangeDataFeed": "true"},\n'
        '    tags={"domain": "sales", "owner": "tom"},\n'
        '    clustered_by=["id"],\n'
        '    primary_key=["id"],\n'
        '    primary_key_name="orders_pk",\n'
        ")\n"
        "\n"
        "all_tables = (orders,)\n"
    )
    assert module.warnings == ()


def test_declared_state_matches_observed_state_for_a_fully_specified_table() -> None:
    # Given a partitioned table with keys, metadata, and tags
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "events"),
        columns=(
            ObservedColumn("event_id", Long(), nullable=False, comment="Event key"),
            ObservedColumn("event_date", Date(), nullable=False),
            ObservedColumn("payload", Struct([StructField("kind", String())])),
        ),
        comment="Event stream.",
        tags={"tier": "gold"},
        partitioned_by=("event_date",),
        primary_key=ObservedPrimaryKeyConstraint(("event_id",), "events_pk"),
        properties={"delta.columnMapping.mode": "name"},
    )

    # When
    module = generate_module(observed)
    declared = _import_declaration(module.source)

    # Then the declaration matches the observed table exactly
    diff = diff_table(declared.to_desired_table(), observed)
    assert diff.actions == ()
    assert diff.unresolvable == ()
    assert module.warnings == ()


def test_foreign_keys_surface_as_warnings_and_commented_source() -> None:
    # Given a table owning one cross-table and one self-referencing foreign key
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "orders"),
        columns=(
            ObservedColumn("id", Long(), nullable=False),
            ObservedColumn("customer_id", Long()),
            ObservedColumn("parent_id", Long()),
        ),
        primary_key=ObservedPrimaryKeyConstraint(("id",), "orders_pk"),
        foreign_keys=(
            ObservedForeignKeyConstraint(
                local_columns=("customer_id",),
                referenced_table=QualifiedName("dev", "sales", "customers"),
                referenced_columns=("id",),
                name="fk_orders_customer",
            ),
            ObservedForeignKeyConstraint(
                local_columns=("parent_id",),
                referenced_table=QualifiedName("dev", "sales", "orders"),
                referenced_columns=("id",),
                name="fk_orders_parent",
            ),
        ),
    )

    # When
    module = generate_module(observed)

    # Then each key is warned about and kept as a commented repair hint
    assert module.warnings == (
        "foreign key fk_orders_customer (customer_id -> dev.sales.customers.id)"
        " is not rendered; planning this module as written will drop it",
        "foreign key fk_orders_parent (parent_id -> dev.sales.orders.id)"
        " is not rendered; planning this module as written will drop it",
    )
    assert (
        '    #     ForeignKey(columns={"customer_id": "id"},'
        ' references=<dev.sales.customers>, name="fk_orders_customer"),\n'
    ) in module.source
    assert (
        '    #     ForeignKey(columns={"parent_id": "id"},'
        ' references=Self, name="fk_orders_parent"),\n'
    ) in module.source

    # Then planning the module as written drops exactly those keys
    declared = _import_declaration(module.source)
    diff = diff_table(declared.to_desired_table(), observed)
    assert diff.actions == (
        DropForeignKey(name="fk_orders_customer"),
        DropForeignKey(name="fk_orders_parent"),
    )
    assert diff.unresolvable == ()


def test_streaming_table_generates_an_annotations_scope_declaration() -> None:
    # Given a streaming table whose structure belongs to its pipeline
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "orders_live"),
        columns=(ObservedColumn("id", Long(), nullable=False, comment="Order key"),),
        comment="Streaming orders.",
        properties={"delta.enableChangeDataFeed": "true"},
        kind=TableKind.STREAMING_TABLE,
    )

    # When
    module = generate_module(observed)

    # Then the module manages annotations only, without the pipeline's properties
    assert '    scope="annotations",\n' in module.source
    assert "properties=" not in module.source
    assert module.warnings == (
        'streaming table: generated with scope="annotations"; structure,'
        " properties, and keys belong to the owning pipeline",
    )

    # Then the declaration matches the observed table exactly
    declared = _import_declaration(module.source)
    diff = diff_table(declared.to_desired_table(), observed)
    assert diff.actions == ()
    assert diff.unresolvable == ()


def test_a_table_the_engine_cannot_declare_fails_generation_with_the_reason() -> None:
    # Given a live table carrying legacy id column mapping
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "legacy"),
        columns=(ObservedColumn("id", Long()),),
        properties={"delta.columnMapping.mode": "id"},
    )

    # Then generation fails closed, naming the table and the reason
    with pytest.raises(GenerationError) as caught:
        generate_module(observed)
    assert "dev.sales.legacy" in str(caught.value)
    assert "columnMapping" in str(caught.value)


def test_a_not_null_struct_field_inside_an_array_fails_generation() -> None:
    # Given a nested schema the engine cannot declare
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "nested"),
        columns=(
            ObservedColumn(
                "payload",
                Array(Struct([StructField("kind", String(), nullable=False)])),
            ),
        ),
    )

    # Then generation fails closed, naming the table
    with pytest.raises(GenerationError) as caught:
        generate_module(observed)
    assert "dev.sales.nested" in str(caught.value)


def test_a_table_name_that_is_not_a_python_identifier_still_binds_a_variable() -> None:
    # Given a table name with a leading digit and a hyphen
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "2024-orders"),
        columns=(ObservedColumn("id", Long()),),
    )

    # When
    module = generate_module(observed)
    declared = _import_declaration(module.source)

    # Then the module binds a valid identifier while declaring the real name
    assert "_2024_orders = DeltaTable(" in module.source
    assert "all_tables = (_2024_orders,)" in module.source
    assert declared.name == "2024-orders"


def test_a_table_named_like_a_python_keyword_still_binds_a_variable() -> None:
    # Given a table whose name is a Python keyword
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "class"),
        columns=(ObservedColumn("id", Long()),),
    )

    # When
    module = generate_module(observed)
    declared = _import_declaration(module.source)

    # Then
    assert "class_ = DeltaTable(" in module.source
    assert declared.name == "class"


def test_every_data_type_round_trips_through_generated_source() -> None:
    # Given one column per concrete data type, on a table whose protocol
    # already supports the features those types require (as a live one would)
    observed = ObservedTable(
        qualified_name=QualifiedName("dev", "sales", "typed"),
        columns=tuple(
            ObservedColumn(f"column_{index}", sample)
            for index, sample in enumerate(_sample_data_types())
        ),
        supported_features=frozenset(TableFeature),
    )

    # When
    module = generate_module(observed)
    declared = _import_declaration(module.source)

    # Then the declaration matches the observed table exactly
    diff = diff_table(declared.to_desired_table(), observed)
    assert diff.actions == ()
    assert diff.unresolvable == ()
