"""Domain value objects representing key constraints (primary and foreign)."""

from dataclasses import dataclass
from typing import Self

from delta_engine.domain.model.qualified_name import QualifiedName


@dataclass(frozen=True, slots=True)
class PrimaryKeyConstraint:
    """
    A primary key constraint declaration.

    Symmetric with :class:`ForeignKeyConstraint`: a table-level key constraint
    over an ordered set of columns.

    Attributes:
        columns: Ordered tuple of column names that make up the primary key.
        constraint_name: The constraint name. Generated by the API layer when a
            ``DeltaTable`` is lowered to a ``DesiredTable`` (``{table}_pk``), and
            read from the catalog for observed constraints.

    """

    columns: tuple[str, ...]
    constraint_name: str

    def __post_init__(self) -> None:
        if not self.columns:
            raise ValueError("columns must not be empty")
        seen: set[str] = set()
        for column in self.columns:
            if column in seen:
                raise ValueError(f"Duplicate primary key column: {column}")
            seen.add(column)
        if not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank")

    @classmethod
    def generate(cls, *, table_name: str, columns: tuple[str, ...]) -> Self:
        """Return a constraint over ``columns`` named ``{table_name}_pk``."""
        return cls(columns=columns, constraint_name=f"{table_name}_pk")


@dataclass(frozen=True, slots=True)
class ForeignKeyConstraint:
    """
    A foreign key constraint declaration.

    Attributes:
        local_columns: Ordered tuple of local column names in the constraint.
        referenced_table: Fully qualified name of the referenced table.
        referenced_columns: Ordered tuple of column names in the referenced
            table, positionally aligned with ``local_columns``.
        constraint_name: The constraint name. Generated by the API layer when a
            ``DeltaTable`` is lowered to a ``DesiredTable``
            (``{table}_{local_cols}_fk``), and read from the catalog for observed
            constraints.

    """

    local_columns: tuple[str, ...]
    referenced_table: QualifiedName
    referenced_columns: tuple[str, ...]
    constraint_name: str

    @classmethod
    def generate(
        cls,
        *,
        owner_table_name: str,
        local_columns: tuple[str, ...],
        referenced_table: QualifiedName,
        referenced_columns: tuple[str, ...],
    ) -> Self:
        """Return a constraint named ``{owner_table_name}_{local_columns}_fk``."""
        columns = "_".join(local_columns)
        return cls(
            local_columns=local_columns,
            referenced_table=referenced_table,
            referenced_columns=referenced_columns,
            constraint_name=f"{owner_table_name}_{columns}_fk",
        )

    def __post_init__(self) -> None:
        if not self.local_columns:
            raise ValueError("local_columns must not be empty")
        if not self.referenced_columns:
            raise ValueError("referenced_columns must not be empty")
        if len(self.local_columns) != len(self.referenced_columns):
            raise ValueError(
                "local_columns and referenced_columns must have the same number of entries;"
                f" got {len(self.local_columns)} local and"
                f" {len(self.referenced_columns)} referenced"
            )
        if not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank")

    @property
    def signature(self) -> tuple[tuple[str, ...], QualifiedName, tuple[str, ...]]:
        """
        Content identity: local columns, referenced table, referenced columns.

        Excludes ``constraint_name``, so a desired foreign key (whose name the
        engine generates) and a catalog-observed one (which carries the
        catalog's name) compare equal when they describe the same relationship.
        """
        return (self.local_columns, self.referenced_table, self.referenced_columns)


@dataclass(frozen=True, slots=True)
class ForeignKeyReference:
    """
    A foreign key on some table that references *this* table's key.

    The inbound counterpart of :class:`ForeignKeyConstraint`: it identifies
    the referencing constraint and its owner without carrying column detail —
    enough for validation to name what blocks a primary-key change.
    """

    constraint_name: str
    referencing_table: QualifiedName

    def __post_init__(self) -> None:
        if not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank")
