"""Domain value objects representing key constraints (primary and foreign)."""

from collections.abc import Iterable
from dataclasses import dataclass

from delta_engine.domain.collection_types import ListOrTuple
from delta_engine.domain.model.identifier import Identifier
from delta_engine.domain.model.qualified_name import QualifiedName

KeySignature = frozenset[str]


def key_signature(columns: Iterable[str]) -> KeySignature:
    """Return the order-independent, case-insensitive identity of a key's columns."""
    return frozenset(Identifier(column) for column in columns)


@dataclass(frozen=True, slots=True)
class PrimaryKeyConstraint:
    """
    A primary key constraint declaration.

    Symmetric with :class:`ForeignKeyConstraint`: a table-level key constraint
    over an ordered set of columns.

    Attributes:
        columns: Ordered tuple of column names, preserving their supplied
            spelling. Identity and duplicates are judged by identifier key.
        constraint_name: Physical constraint name, preserving its spelling.
            Public declarations generate the default ``{table}_pk`` name before
            constructing this domain value.

    """

    columns: ListOrTuple[str]
    constraint_name: str

    @property
    def signature(self) -> KeySignature:
        """Content identity, excluding physical name and declaration order."""
        return key_signature(self.columns)

    def __post_init__(self) -> None:
        columns = tuple(Identifier(column) for column in self.columns)
        if not columns:
            raise ValueError("columns must not be empty")

        seen: set[str] = set()
        for column in columns:
            if column in seen:
                raise ValueError(f"Duplicate primary key column: {column}")
            seen.add(column)

        if not isinstance(self.constraint_name, str):
            raise TypeError("constraint_name must be a string")

        if not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank")

        object.__setattr__(self, "columns", columns)
        object.__setattr__(self, "constraint_name", Identifier(self.constraint_name))


@dataclass(frozen=True, slots=True)
class ForeignKeyConstraint:
    """
    A foreign key constraint declaration.

    Attributes:
        local_columns: Tuple of local column names in the constraint,
            preserving spelling and stored sorted by identifier key (pairing
            with ``referenced_columns`` preserved). Column order is not part of
            a foreign key's meaning, mirroring the primary key's set identity,
            so identity, generated names, and rendered DDL are independent of
            declaration order.
        referenced_table: Fully qualified name of the referenced table.
        referenced_columns: Tuple of column names in the referenced table,
            positionally aligned with ``local_columns`` after identity-key sorting.
        constraint_name: The constraint name, preserved verbatim. Generated by
            the API layer when a ``DeltaTable`` is lowered to a ``DesiredTable``
            (``{table}_{local_cols}_fk``), and read from the catalog for observed
            constraints. Excluded from ``signature``, so a desired and an
            observed constraint still match by content even though constraint
            names preserve their spelling — no migration churn for existing
            catalogs.

    """

    local_columns: ListOrTuple[str]
    referenced_table: QualifiedName
    referenced_columns: ListOrTuple[str]
    constraint_name: str

    def __post_init__(self) -> None:
        local_columns = tuple(Identifier(column) for column in self.local_columns)
        referenced_columns = tuple(Identifier(column) for column in self.referenced_columns)

        if not local_columns:
            raise ValueError("local_columns must not be empty")

        if not referenced_columns:
            raise ValueError("referenced_columns must not be empty")

        if len(local_columns) != len(referenced_columns):
            raise ValueError(
                "local_columns and referenced_columns must have the same number of entries;"
                f" got {len(local_columns)} local and"
                f" {len(referenced_columns)} referenced"
            )

        # Pairs are stored sorted by the local column's identity key. Column
        # order is not part of a foreign key's meaning (mirroring the primary
        # key's set identity), so one canonical order makes identity,
        # generated names, and rendered DDL independent of declaration order
        # and case — while both original spellings are retained.
        pairs = sorted(
            zip(local_columns, referenced_columns, strict=True),
            key=lambda pair: pair[0].lower(),
        )

        seen_local: set[str] = set()
        for column in local_columns:
            if column in seen_local:
                raise ValueError(f"Duplicate foreign key local column: {column}")
            seen_local.add(column)

        seen_referenced: set[str] = set()
        for column in referenced_columns:
            if column in seen_referenced:
                raise ValueError(f"Duplicate foreign key referenced column: {column}")
            seen_referenced.add(column)

        if not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank")

        object.__setattr__(self, "local_columns", tuple(pair[0] for pair in pairs))
        object.__setattr__(self, "referenced_columns", tuple(pair[1] for pair in pairs))
        object.__setattr__(self, "constraint_name", Identifier(self.constraint_name))

    @property
    def signature(self) -> tuple[tuple[str, ...], QualifiedName, tuple[str, ...]]:
        """
        Content identity: local columns, referenced table, referenced columns.

        Column entries are Identifiers, so a desired constraint and a
        catalog-observed one compare equal across display casing. Excludes
        ``constraint_name`` so generated and catalog names still match by
        content.
        """
        return (
            tuple(self.local_columns),
            self.referenced_table,
            tuple(self.referenced_columns),
        )  # TODO: namedTuple instead?

    @property
    def referenced_key_signature(self) -> KeySignature:
        """Identity of the primary key targeted by this foreign key."""
        return key_signature(self.referenced_columns)


@dataclass(frozen=True, slots=True)
class ForeignKeyReference:
    """
    A foreign key on some table that references *this* table's key.

    The inbound counterpart of :class:`ForeignKeyConstraint`: it identifies
    the referencing constraint and its owner without carrying column detail —
    enough for validation to name what blocks a primary-key change.

    Attributes:
        constraint_name: The referencing constraint's name, as read from the
            catalog.
        referencing_table: Fully qualified name of the table that owns the
            referencing constraint.

    """

    constraint_name: str
    referencing_table: QualifiedName

    def __post_init__(self) -> None:
        if not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank")
        object.__setattr__(self, "constraint_name", Identifier(self.constraint_name))
