"""Domain value objects representing key constraints (primary and foreign)."""

from collections.abc import Iterable
from dataclasses import dataclass

from delta_engine.domain.collection_types import ListOrTuple
from delta_engine.domain.model.identifier import Identifier
from delta_engine.domain.model.qualified_name import QualifiedName


def _constraint_columns(columns: object, *, kind: str) -> tuple[Identifier, ...]:
    """Normalize one non-empty, unique list or tuple of constraint columns."""
    if isinstance(columns, str) or not isinstance(columns, (list, tuple)):
        raise TypeError(f"{kind} columns must be a list or tuple of strings")
    if not columns:
        raise ValueError(f"{kind} columns must not be empty")
    if not all(isinstance(column, str) for column in columns):
        raise TypeError(f"{kind} column names must be strings")

    normalized = tuple(Identifier(column) for column in columns)
    seen: set[Identifier] = set()
    for column in normalized:
        if column in seen:
            raise ValueError(f"Duplicate {kind} column: {column}")
        seen.add(column)
    return normalized


@dataclass(frozen=True, slots=True, eq=False)
class PrimaryKeyConstraint:
    """
    A primary key constraint declaration.

    Symmetric with :class:`ForeignKeyConstraint`: a table-level key constraint
    over an ordered set of columns.

    Attributes:
        columns: Ordered tuple of column names, preserving their supplied
            spelling. Identity and duplicates are judged by identifier key.
        constraint_name: Physical constraint name, preserving its spelling.
            Public declarations generate the default ``{table}_pk`` name before
            constructing this domain value.

    """

    columns: ListOrTuple[str]
    constraint_name: str

    def matches_columns(self, columns: Iterable[str]) -> bool:
        """Return whether columns identify this key, ignoring order and case."""
        return frozenset(self.columns) == frozenset(Identifier(column) for column in columns)

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, PrimaryKeyConstraint):
            return NotImplemented
        return self.constraint_name == other.constraint_name and self.matches_columns(other.columns)

    def __hash__(self) -> int:
        return hash((self.constraint_name, frozenset(self.columns)))

    def __post_init__(self) -> None:
        columns = _constraint_columns(self.columns, kind="primary key")
        constraint_name = Identifier(self.constraint_name)

        object.__setattr__(self, "columns", columns)
        object.__setattr__(self, "constraint_name", constraint_name)


@dataclass(frozen=True, slots=True)
class ForeignKeyConstraint:
    """
    A foreign key constraint declaration.

    Attributes:
        local_columns: Tuple of local column names in the constraint,
            preserving spelling and stored sorted by identifier key (pairing
            with ``referenced_columns`` preserved). Column order is not part of
            a foreign key's meaning, mirroring the primary key's set identity,
            so identity, generated names, and rendered DDL are independent of
            declaration order.
        referenced_table: Fully qualified name of the referenced table.
        referenced_columns: Tuple of column names in the referenced table,
            positionally aligned with ``local_columns`` after identity-key sorting.
        constraint_name: The constraint name, preserved verbatim. Generated by
            the API layer when a ``DeltaTable`` is lowered to a ``DesiredTable``
            (``{table}_{local_cols}_fk``) unless explicitly supplied, and read
            from the catalog for observed constraints.

    """

    local_columns: ListOrTuple[str]
    referenced_table: QualifiedName
    referenced_columns: ListOrTuple[str]
    constraint_name: str

    def __post_init__(self) -> None:
        local_columns = _constraint_columns(self.local_columns, kind="foreign key local")
        referenced_columns = _constraint_columns(
            self.referenced_columns,
            kind="foreign key referenced",
        )

        if len(local_columns) != len(referenced_columns):
            raise ValueError(
                "local_columns and referenced_columns must have the same number of entries;"
                f" got {len(local_columns)} local and"
                f" {len(referenced_columns)} referenced"
            )

        # Pairs are stored sorted by the local column's identity key. Column
        # order is not part of a foreign key's meaning (mirroring the primary
        # key's set identity), so one canonical order makes identity,
        # generated names, and rendered DDL independent of declaration order
        # and case — while both original spellings are retained.
        pairs = sorted(
            zip(local_columns, referenced_columns, strict=True),
            key=lambda pair: pair[0].lower(),
        )

        constraint_name = Identifier(self.constraint_name)

        object.__setattr__(self, "local_columns", tuple(pair[0] for pair in pairs))
        object.__setattr__(self, "referenced_columns", tuple(pair[1] for pair in pairs))
        object.__setattr__(self, "constraint_name", constraint_name)


@dataclass(frozen=True, slots=True)
class ForeignKeyReference:
    """
    A foreign key on some table that references *this* table's key.

    The inbound counterpart of :class:`ForeignKeyConstraint`: it identifies
    the referencing constraint and its owner without carrying column detail —
    enough for validation to name what blocks a primary-key change.

    Attributes:
        constraint_name: The referencing constraint's name, as read from the
            catalog.
        referencing_table: Fully qualified name of the table that owns the
            referencing constraint.

    """

    constraint_name: str
    referencing_table: QualifiedName

    def __post_init__(self) -> None:
        object.__setattr__(self, "constraint_name", Identifier(self.constraint_name))
