"""Domain value objects representing foreign key constraints."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from typing import Self

from delta_engine.domain.model.qualified_name import QualifiedName


@dataclass(frozen=True, slots=True)
class ReferencedKey:
    """
    The key targeted by a foreign key constraint.

    Attributes:
        table: Fully qualified referenced table name.
        columns: Ordered tuple of column names in the referenced table.

    """

    table: QualifiedName
    columns: tuple[str, ...]

    def __post_init__(self) -> None:
        """Validate that the referenced key names at least one unique lowercase column."""
        if not self.columns:
            raise ValueError("referenced columns must not be empty")
        seen: set[str] = set()
        for column in self.columns:
            if not column.strip():
                raise ValueError(f"referenced column must not be blank: {column!r}")
            if column != column.casefold():
                raise ValueError(f"referenced column must be lowercase: {column!r}")
            if column in seen:
                raise ValueError(f"Duplicate referenced column: {column}")
            seen.add(column)


@dataclass(frozen=True, slots=True, init=False)
class ForeignKeyConstraint:
    """
    A foreign key constraint declaration.

    Attributes:
        local_columns: Ordered tuple of local column names in the constraint.
        references: The referenced table key, including table name and referenced
            columns positionally aligned with ``local_columns``.
        constraint_name: The constraint name. Populated from the catalog for an
            observed constraint, and generated by the engine
            (``{table}_{local_cols}_fk``) for a desired one; ``None`` only on a
            freshly-declared desired constraint before :meth:`with_generated_name`
            fills it in.

    """

    local_columns: tuple[str, ...]
    references: ReferencedKey
    constraint_name: str | None = None

    def __init__(
        self,
        local_columns: Iterable[str],
        references: ReferencedKey | QualifiedName | str,
        referenced_columns: Iterable[str] | None = None,
        constraint_name: str | None = None,
    ) -> None:
        """
        Create a foreign key constraint.

        ``references`` is stored as a structured :class:`ReferencedKey`. For a
        migration window, callers may still pass a dotted string or
        :class:`QualifiedName` plus ``referenced_columns``; both are immediately
        lowered into a structured reference.
        """
        object.__setattr__(self, "local_columns", tuple(local_columns))
        object.__setattr__(
            self,
            "references",
            _coerce_referenced_key(references, referenced_columns),
        )
        object.__setattr__(self, "constraint_name", constraint_name)
        self.__post_init__()

    @property
    def referenced_table(self) -> QualifiedName:
        """Return the referenced table's fully qualified name."""
        return self.references.table

    @property
    def referenced_columns(self) -> tuple[str, ...]:
        """Return the referenced column names, aligned to ``local_columns``."""
        return self.references.columns

    def with_generated_name(self, table_name: str) -> Self:
        """
        Return a copy carrying the engine-generated name ``{table}_{local_cols}_fk``.

        Desired-side constraint names are generated by the engine, not supplied by
        the user (user-defined names are a future feature), so a constraint that
        already carries a name is rejected rather than silently overwritten.
        """
        if self.constraint_name is not None:
            raise ValueError(
                "foreign key constraint_name is generated by the engine, not user-defined;"
                f" leave it unset (got {self.constraint_name!r})"
            )
        columns = "_".join(self.local_columns)
        return type(self)(
            local_columns=self.local_columns,
            references=self.references,
            constraint_name=f"{table_name}_{columns}_fk",
        )

    def __post_init__(self) -> None:
        if not self.local_columns:
            raise ValueError("local_columns must not be empty")
        seen: set[str] = set()
        for column in self.local_columns:
            if not column.strip():
                raise ValueError(f"local column must not be blank: {column!r}")
            if column != column.casefold():
                raise ValueError(f"local column must be lowercase: {column!r}")
            if column in seen:
                raise ValueError(f"Duplicate local column: {column}")
            seen.add(column)
        if len(self.local_columns) != len(self.referenced_columns):
            raise ValueError(
                "local_columns and referenced columns must have the same number of entries;"
                f" got {len(self.local_columns)} local and"
                f" {len(self.referenced_columns)} referenced"
            )
        if self.constraint_name is not None and not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank when provided")

    @property
    def signature(self) -> tuple[tuple[str, ...], QualifiedName, tuple[str, ...]]:
        """
        Content identity: local columns, referenced table, referenced columns.

        Excludes ``constraint_name``, so a declared foreign key (which may be
        unnamed) and a catalog-observed one (which always carries a name)
        compare equal when they describe the same relationship. This makes the
        constraint's identity independent of how it happens to be named.
        """
        return (self.local_columns, self.referenced_table, self.referenced_columns)


def _coerce_referenced_key(
    references: ReferencedKey | QualifiedName | str,
    referenced_columns: Iterable[str] | None,
) -> ReferencedKey:
    """Normalize supported reference inputs into a structured referenced key."""
    if isinstance(references, ReferencedKey):
        if referenced_columns is not None:
            raise ValueError("referenced_columns must not be provided with ReferencedKey")
        return references
    if isinstance(references, str):
        return ReferencedKey(
            table=QualifiedName.parse(references),
            columns=_required_referenced_columns(referenced_columns, references),
        )
    if isinstance(references, QualifiedName):
        return ReferencedKey(
            table=references,
            columns=_required_referenced_columns(referenced_columns, str(references)),
        )
    raise TypeError(f"references must be ReferencedKey, QualifiedName, or str; got {references!r}")


def _required_referenced_columns(
    referenced_columns: Iterable[str] | None, references: str
) -> tuple[str, ...]:
    """Return referenced columns or raise a reference-specific error."""
    columns = tuple(referenced_columns) if referenced_columns is not None else ()
    if not columns:
        raise ValueError(f"referenced_columns must be provided for foreign key reference {references}")
    return columns
