"""Domain value object representing a foreign key constraint."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Self

from delta_engine.domain.model.qualified_name import QualifiedName


@dataclass(frozen=True, slots=True)
class ForeignKeyConstraint:
    """
    A foreign key constraint declaration.

    Attributes:
        local_columns: Ordered tuple of local column names in the constraint.
        referenced_table: Fully qualified name of the referenced table.
        referenced_columns: Ordered tuple of column names in the referenced
            table, positionally aligned with ``local_columns``.
        constraint_name: The constraint name. Populated from the catalog for an
            observed constraint, and generated by the engine
            (``{table}_{local_cols}_fk``) for a desired one; ``None`` only on a
            freshly-declared desired constraint before :meth:`with_generated_name`
            fills it in.

    """

    local_columns: tuple[str, ...]
    referenced_table: QualifiedName
    referenced_columns: tuple[str, ...]
    constraint_name: str | None = None

    @classmethod
    def generate(
        cls,
        *,
        owner_table_name: str,
        local_columns: tuple[str, ...],
        referenced_table: QualifiedName,
        referenced_columns: tuple[str, ...],
    ) -> Self:
        """Return a constraint named ``{owner_table_name}_{local_columns}_fk``."""
        columns = "_".join(local_columns)
        return cls(
            local_columns=local_columns,
            referenced_table=referenced_table,
            referenced_columns=referenced_columns,
            constraint_name=f"{owner_table_name}_{columns}_fk",
        )

    def with_generated_name(self, table_name: str) -> Self:
        """
        Return a copy carrying the engine-generated name ``{table}_{local_cols}_fk``.

        Delegates to :meth:`generate`. Rejects an already-named constraint so a
        user-supplied name fails loudly rather than being silently overwritten.
        """
        if self.constraint_name is not None:
            raise ValueError(
                "foreign key constraint_name is generated by the engine, not user-defined;"
                f" leave it unset (got {self.constraint_name!r})"
            )
        return type(self).generate(
            owner_table_name=table_name,
            local_columns=self.local_columns,
            referenced_table=self.referenced_table,
            referenced_columns=self.referenced_columns,
        )

    def __post_init__(self) -> None:
        if not self.local_columns:
            raise ValueError("local_columns must not be empty")
        if not self.referenced_columns:
            raise ValueError("referenced_columns must not be empty")
        if len(self.local_columns) != len(self.referenced_columns):
            raise ValueError(
                "local_columns and referenced_columns must have the same number of entries;"
                f" got {len(self.local_columns)} local and"
                f" {len(self.referenced_columns)} referenced"
            )
        if self.constraint_name is not None and not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank when provided")

    @property
    def signature(self) -> tuple[tuple[str, ...], QualifiedName, tuple[str, ...]]:
        """
        Content identity: local columns, referenced table, referenced columns.

        Excludes ``constraint_name``, so a declared foreign key (which may be
        unnamed) and a catalog-observed one (which always carries a name)
        compare equal when they describe the same relationship.
        """
        return (self.local_columns, self.referenced_table, self.referenced_columns)
