"""Domain value object representing a primary key constraint."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Self


@dataclass(frozen=True, slots=True)
class PrimaryKeyConstraint:
    """
    A primary key constraint declaration.

    Symmetric with :class:`ForeignKeyConstraint`: a table-level key constraint
    over an ordered set of columns.

    Attributes:
        columns: Ordered tuple of column names that make up the primary key.
        constraint_name: The constraint name. Populated from the catalog for an
            observed constraint, and generated by the engine (``{table}_pk``) for a
            desired one; ``None`` only on a freshly-declared desired constraint before
            :meth:`with_generated_name` fills it in.

    """

    columns: tuple[str, ...]
    constraint_name: str | None = None

    def __post_init__(self) -> None:
        if not self.columns:
            raise ValueError("columns must not be empty")
        seen: set[str] = set()
        for column in self.columns:
            if column in seen:
                raise ValueError(f"Duplicate primary key column: {column}")
            seen.add(column)
        if self.constraint_name is not None and not self.constraint_name.strip():
            raise ValueError("constraint_name must not be blank when provided")

    @classmethod
    def generate(cls, *, table_name: str, columns: tuple[str, ...]) -> Self:
        """Return a constraint over ``columns`` named ``{table_name}_pk``."""
        return cls(columns=columns, constraint_name=f"{table_name}_pk")

    def with_generated_name(self, table_name: str) -> Self:
        """
        Return a copy carrying the engine-generated constraint name ``{table}_pk``.

        Delegates to :meth:`generate`. Rejects an already-named constraint so a
        user-supplied name fails loudly rather than being silently overwritten.
        """
        if self.constraint_name is not None:
            raise ValueError(
                "primary key constraint_name is generated by the engine, not user-defined;"
                f" leave it unset (got {self.constraint_name!r})"
            )
        return type(self).generate(table_name=table_name, columns=self.columns)
