"""Domain models for table snapshots and derivatives."""

from collections.abc import Mapping
from dataclasses import dataclass, field

from delta_engine.domain.model.column import Column
from delta_engine.domain.model.constraints import ForeignKeyConstraint, PrimaryKeyConstraint
from delta_engine.domain.model.data_type import Array, Map, Struct, Variant
from delta_engine.domain.model.qualified_name import QualifiedName
from delta_engine.domain.model.table_aspect import ALL_ASPECTS, TableAspect

# Complex types Delta cannot partition by (DELTA_INVALID_PARTITION_COLUMN_TYPE).
_UNPARTITIONABLE_TYPES = (Array, Map, Struct, Variant)


@dataclass(frozen=True, slots=True)
class TableSnapshot:
    """
    Immutable snapshot of a table schema.

    Attributes:
        qualified_name: Fully qualified table name.
        columns: Ordered tuple of ``Column`` definitions.
        comment: Optional table-level comment (empty string when unset).
        tags: Read-only mapping of Unity Catalog tag keys to values.
        partitioned_by: Ordered tuple of partition column names.
        primary_key: Primary key constraint, or ``None`` when no primary key is defined.

    Properties live on the subclasses, not here: a desired table's mapping
    accepts ``None`` values (absence assertions) while an observed table's
    carries catalog values only — the two types differ.

    """

    qualified_name: QualifiedName
    columns: tuple[Column, ...]
    comment: str = ""
    tags: Mapping[str, str] = field(default_factory=dict)
    partitioned_by: tuple[str, ...] = ()
    primary_key: PrimaryKeyConstraint | None = None
    foreign_keys: tuple[ForeignKeyConstraint, ...] = ()

    @property
    def primary_key_columns(self) -> tuple[str, ...]:
        """Primary key column names, or ``()`` when the table has no primary key."""
        return self.primary_key.columns if self.primary_key is not None else ()

    def __post_init__(self) -> None:
        """
        Validate the snapshot's structural invariants.

        Columns must be non-empty and unique; partition columns must be
        lowercase, must each exist in ``columns``, and must be unique.
        Primary key columns must each exist in ``columns``.
        """
        if not self.columns:
            raise ValueError("Table requires at least one column")

        seen_names: set[str] = set()
        for column in self.columns:
            if column.name in seen_names:
                raise ValueError(f"Duplicate column name: {column.name}")
            seen_names.add(column.name)

        for name in self.partitioned_by:
            if name != name.casefold():
                raise ValueError(f"Partition column name must be lowercase: {name!r}")

        missing = [name for name in self.partitioned_by if name not in seen_names]
        if missing:
            raise ValueError(f"Partition column not found: {missing[0]}")

        seen_partitions: set[str] = set()
        for name in self.partitioned_by:
            if name in seen_partitions:
                raise ValueError(f"Duplicate partition column: {name}")
            seen_partitions.add(name)

        if self.primary_key is not None:
            missing_pk = [name for name in self.primary_key.columns if name not in seen_names]
            if missing_pk:
                raise ValueError(f"Primary key column not found in columns: {missing_pk[0]}")

        for foreign_key in self.foreign_keys:
            missing = [col for col in foreign_key.local_columns if col not in seen_names]
            if missing:
                raise ValueError(f"Foreign key local column not found in columns: {missing[0]}")

        for tag_key in self.tags:
            if not tag_key.strip():
                raise ValueError(f"Tag key must not be blank: {tag_key!r}")


@dataclass(frozen=True, slots=True)
class DesiredTable(TableSnapshot):
    """
    Desired definition authored by users (target state).

    A desired table's key constraints arrive already named: the constraint name
    is generated by the API layer when a ``DeltaTable`` is lowered. The differ
    and compiler read the name off desired constraints rather than deriving it
    themselves.

    A ``None`` property value asserts the key must be absent from the table.
    """

    properties: Mapping[str, str | None] = field(default_factory=dict)
    managed_aspects: frozenset[TableAspect] = field(default_factory=lambda: ALL_ASPECTS)

    def __post_init__(self) -> None:
        """
        Enforce desired-only invariants.

        No two foreign keys may govern the same set of local columns. Two FKs
        over the same local columns are incoherent, and would generate the same
        constraint name (``{table}_{local_cols}_fk``) and collide at DDL time.
        Checking the column *set* (order-insensitive) also rejects a reordered
        duplicate.

        A primary key column must be NOT NULL — a nullable primary key is not a
        well-formed desired schema, independent of any migration. Enforcing it
        here (rather than as a plan-validation rule) keeps the planning layer
        free of column-nullability lookups. Both checks live on DesiredTable,
        not the shared base: an observed table may legitimately carry such a
        layout (a legacy catalog schema) and must stay representable.

        Partition columns must not have complex types (Array, Map, Struct, Variant)
        and at least one non-partition column must exist.
        """
        TableSnapshot.__post_init__(self)
        if not self.managed_aspects:
            raise ValueError(
                "managed_aspects must not be empty: a table that manages no aspect"
                " declares nothing for the engine to do"
            )
        seen: set[frozenset[str]] = set()
        for foreign_key in self.foreign_keys:
            local_column_set = frozenset(foreign_key.local_columns)
            if local_column_set in seen:
                raise ValueError(
                    "Two foreign keys declared over the same local columns:"
                    f" {sorted(local_column_set)}"
                )
            seen.add(local_column_set)

        if self.primary_key is not None:
            key_columns = set(self.primary_key.columns)
            nullable_key_columns = [
                column.name
                for column in self.columns
                if column.name in key_columns and column.nullable
            ]
            if nullable_key_columns:
                raise ValueError(
                    "Primary key column must be NOT NULL:"
                    f" {nullable_key_columns[0]}. Set nullable=False on every"
                    " primary key column."
                )

        columns_by_name = {column.name: column for column in self.columns}
        for name in self.partitioned_by:
            data_type = columns_by_name[name].data_type
            if isinstance(data_type, _UNPARTITIONABLE_TYPES):
                raise ValueError(
                    f"Partition column {name!r} has type"
                    f" {type(data_type).__name__}, which Delta cannot"
                    " partition by"
                )
        if self.partitioned_by and len(self.partitioned_by) == len(self.columns):
            raise ValueError(
                "Cannot partition by every column: at least one non-partition column is required"
            )


@dataclass(frozen=True, slots=True)
class ObservedTable(TableSnapshot):
    """Observed definition derived from the catalog (current state)."""

    properties: Mapping[str, str] = field(default_factory=dict)
